### ISSUE TITLE
Version 2.9.7 not pushed?

### ISSUE THREAD

**Issue by NigelCunningham** [superawesomeme/moodle-theme_aardvark#6]
Thanks for your work on this theme.

https://moodle.org/plugins/pluginversion.php?id=9710 advertises a version 2.9.7 but the latest code here is 2.9.6. Could you have forgotten to git push?

Thanks!

Nigel

**Comment by lazydaisy** [comment]
Hi Shaun, can you please update your Aardvark github so that I can push the changes for the logo filepicker ready for 3.1?
Cheers
Mary

**Comment by superawesomeme** [comment]
Done, updated. Sorry it took so long.
